"""empty message

Revision ID: 0b5a75f5542e
Revises: 53eb7402cb23
Create Date: 2021-05-25 20:54:19.703598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b5a75f5542e'
down_revision = '53eb7402cb23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('status', sa.Enum('Active', 'Expired'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'status')
    # ### end Alembic commands ###
