"""empty message

Revision ID: 0f6bdd1335b1
Revises: 8f794563687a
Create Date: 2021-05-26 14:39:40.525821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f6bdd1335b1'
down_revision = '8f794563687a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_user')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grrno', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint(None, ['grrno'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('grrno')

    op.create_table('_alembic_tmp_user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('firstname', sa.VARCHAR(), nullable=False),
    sa.Column('lastname', sa.VARCHAR(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=128), nullable=True),
    sa.Column('dob', sa.DATETIME(), nullable=False),
    sa.Column('mobileno', sa.VARCHAR(length=10), nullable=False),
    sa.Column('House', sa.VARCHAR(length=10), nullable=True),
    sa.Column('Class', sa.INTEGER(), nullable=False),
    sa.Column('Section', sa.VARCHAR(length=1), nullable=False),
    sa.Column('Rollno', sa.INTEGER(), nullable=False),
    sa.Column('aadharcard', sa.INTEGER(), nullable=False),
    sa.Column('gender', sa.VARCHAR(length=6), nullable=True),
    sa.Column('image_file', sa.VARCHAR(length=20), nullable=False),
    sa.Column('grrno', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('aadharcard'),
    sa.UniqueConstraint('grrno', name='uq_user_grrno'),
    sa.UniqueConstraint('mobileno')
    )
    # ### end Alembic commands ###
