"""empty message

Revision ID: 251c80a1b276
Revises: c7539d8d19f1
Create Date: 2021-05-26 12:59:49.773786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '251c80a1b276'
down_revision = 'c7539d8d19f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grrno', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint(None, ['grrno'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('grrno')

    # ### end Alembic commands ###
