"""empty message

Revision ID: 734606efd4e2
Revises: 0b5a75f5542e
Create Date: 2021-05-26 10:55:35.729908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '734606efd4e2'
down_revision = '0b5a75f5542e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('registrationstart', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'registrationstart')
    # ### end Alembic commands ###
