"""empty message

Revision ID: 9260a71e71f4
Revises: 734606efd4e2
Create Date: 2021-05-26 10:55:54.435842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9260a71e71f4'
down_revision = '734606efd4e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('registrationend', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'registrationend')
    # ### end Alembic commands ###
