"""empty message

Revision ID: 934c7f5aa0e7
Revises: 9260a71e71f4
Create Date: 2021-05-26 11:14:09.762547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '934c7f5aa0e7'
down_revision = '9260a71e71f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('event_description', sa.Text(), nullable=True))
    op.drop_column('events', 'event_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('event_name', sa.VARCHAR(), nullable=True))
    op.drop_column('events', 'event_description')
    # ### end Alembic commands ###
