"""empty message

Revision ID: c7539d8d19f1
Revises: 934c7f5aa0e7
Create Date: 2021-05-26 11:27:41.737783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7539d8d19f1'
down_revision = '934c7f5aa0e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('event_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_name', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
